/**
 * Kai object envelopes: build, persist, and derive.
 *
 * Envelope shape is 02 §7: {id, type, created_at, model, prompt_version,
 * disclosures[], refs, payload}.
 */
import {
  KaiObjectEnvelope,
  type GradedSetupPayload,
  type KaiObjectType,
  type ExplainLevels,
} from '@shared/api';
import { serviceClient } from '../db';
import { log } from '../log';
import { KAI_MODEL, KAI_PROMPT_VERSION } from '../env';
import { quoteFromSnapshot } from '../market';
import { entryPrice, invalidationPrice, normalizeTargets, type SetupRow } from './context';

/** Objects derived from database rows rather than generated by the model. */
export const DETERMINISTIC_MODEL = 'deterministic/v1';

export const DISCLOSURES = {
  paperOnly: 'paper_only',
  education: 'education_not_advice',
} as const;

export function envelope(opts: {
  id: string;
  type: KaiObjectType;
  payload: unknown;
  model?: string;
  createdAt?: string;
  refs?: Record<string, unknown> | null;
  disclosures?: string[];
}): KaiObjectEnvelope {
  return KaiObjectEnvelope.parse({
    id: opts.id,
    type: opts.type,
    created_at: opts.createdAt ?? new Date().toISOString(),
    model: opts.model ?? KAI_MODEL(),
    prompt_version: KAI_PROMPT_VERSION,
    disclosures: opts.disclosures ?? [DISCLOSURES.paperOnly, DISCLOSURES.education],
    refs: opts.refs ?? null,
    payload: opts.payload,
  });
}

/** Persist a generated object to `kai_objects` and return its envelope. */
export async function persistKaiObject(opts: {
  type: KaiObjectType;
  payload: unknown;
  userId: string | null;
  refs?: Record<string, unknown> | null;
  model?: string;
  disclosures?: string[];
  requestId?: string;
}): Promise<KaiObjectEnvelope | null> {
  try {
    const db = serviceClient();
    const { data, error } = await db
      .from('kai_objects')
      .insert({
        type: opts.type,
        payload: opts.payload as never,
        disclosures: opts.disclosures ?? [DISCLOSURES.paperOnly, DISCLOSURES.education],
        model: opts.model ?? KAI_MODEL(),
        prompt_version: KAI_PROMPT_VERSION,
        refs: (opts.refs ?? null) as never,
        user_id: opts.userId,
      })
      .select('id,type,payload,disclosures,model,prompt_version,refs,created_at')
      .single();
    if (error || !data) {
      log('error', opts.requestId ?? '-', 'kai_object.persist_failed', {
        type: opts.type,
        message: error?.message,
      });
      return null;
    }
    const row = data as unknown as {
      id: string;
      type: KaiObjectType;
      payload: unknown;
      disclosures: string[];
      model: string;
      prompt_version: string;
      refs: Record<string, unknown> | null;
      created_at: string;
    };
    return envelope({
      id: row.id,
      type: row.type,
      payload: row.payload,
      model: row.model,
      createdAt: row.created_at,
      refs: row.refs,
      disclosures: row.disclosures,
    });
  } catch (e) {
    log('error', opts.requestId ?? '-', 'kai_object.persist_threw', {
      type: opts.type,
      message: e instanceof Error ? e.message : String(e),
    });
    return null;
  }
}

/** Look up a cached object by exact refs match (used for the daily briefing). */
export async function findCachedObject(
  type: KaiObjectType,
  refs: Record<string, unknown>
): Promise<KaiObjectEnvelope | null> {
  const db = serviceClient();
  const { data, error } = await db
    .from('kai_objects')
    .select('id,type,payload,disclosures,model,prompt_version,refs,created_at')
    .eq('type', type)
    .contains('refs', refs as never)
    .order('created_at', { ascending: false })
    .limit(1);
  if (error || !data || data.length === 0) return null;
  const row = data[0] as unknown as {
    id: string;
    type: KaiObjectType;
    payload: unknown;
    disclosures: string[];
    model: string;
    refs: Record<string, unknown> | null;
    created_at: string;
  };
  return envelope({
    id: row.id,
    type: row.type,
    payload: row.payload,
    model: row.model,
    createdAt: row.created_at,
    refs: row.refs,
    disclosures: row.disclosures,
  });
}

/* ------------------------------------------------------------------ */
/* Deterministic graded_setup derived from a setups row               */
/* ------------------------------------------------------------------ */

function moneyRisk(entry: number | null, stop: number | null): number | null {
  if (entry === null || stop === null) return null;
  const per = Math.abs(entry - stop);
  return Number.isFinite(per) ? Math.round(per * 100) / 100 : null;
}

const STATE_ACTION: Record<string, string> = {
  discovered: 'Just spotted — I am still watching it',
  watching: 'Watching for the first sign of strength',
  forming: 'Waiting for confirmation',
  ready: 'Conditions are met — your move',
  invalidated: 'This one is off — the level failed',
  expired: 'The window for this one has closed',
};

/**
 * Build a graded_setup payload straight from the row. No model call, no
 * invented numbers: every value is either in the row or composed from the
 * row's own text. `explain` is used from the row when the scanner supplied it
 * (annotations.explain / score_components.explain), otherwise composed.
 */
export function gradedSetupFromRow(row: SetupRow, annotations?: unknown): GradedSetupPayload {
  const quote = quoteFromSnapshot(row.symbol, row.quote_snapshot);
  const entry = entryPrice(row.entry_condition);
  const stop = row.stop ?? invalidationPrice(row.invalidation);
  const targets = normalizeTargets(row.targets);
  const risk = moneyRisk(entry, stop);
  const long = row.intent === 'buy_to_open' || row.intent === 'buy_to_cover';
  const supplied = extractExplain(annotations) ?? extractExplain(row.score_components);

  const thesis = row.thesis_plain ?? `${row.symbol} is on my list.`;
  const invalidText =
    stop !== null
      ? `It fails ${long ? 'below' : 'above'} $${stop}${risk !== null ? ` — about $${risk} per share if you are wrong` : ''}.`
      : 'I do not have an invalidation level on this one yet.';

  const explain: ExplainLevels = supplied ?? {
    beginner: `${thesis} ${invalidText}`,
    intermediate: `${thesis} ${entry !== null ? `The trigger is ${long ? 'above' : 'below'} $${entry}. ` : ''}${invalidText}`,
    advanced: row.thesis_technical ?? `${thesis} ${invalidText}`,
    family:
      `Think of $${entry ?? '—'} as a doorway. ` +
      `${long ? 'Above' : 'Below'} it, the crowd is in charge in our direction; on the other side of $${stop ?? '—'} they are not. ` +
      `We do not guess — we wait and we know what being wrong costs.`,
  };

  return {
    setup_id: row.id,
    symbol: row.symbol,
    mode: row.mode,
    intent: row.intent as GradedSetupPayload['intent'],
    state: row.state as GradedSetupPayload['state'],
    grade_band: (row.grade_band as GradedSetupPayload['grade_band']) ?? null,
    grade_display: row.grade_display ?? null,
    score: row.score ?? null,
    thesis_plain: thesis,
    thesis_technical: row.thesis_technical ?? null,
    entry,
    entry_condition: row.entry_condition ?? null,
    stop,
    invalidation: row.invalidation ?? null,
    targets,
    next_action: `${STATE_ACTION[row.state] ?? 'Watching'}${risk !== null ? ` · risk $${risk} if wrong` : ''}`,
    risk_plain: invalidText,
    est_risk_usd: risk,
    quote,
    explain,
  };
}

function extractExplain(source: unknown): ExplainLevels | null {
  if (!source || typeof source !== 'object') return null;
  const e = (source as Record<string, unknown>).explain;
  if (!e || typeof e !== 'object') return null;
  const o = e as Record<string, unknown>;
  const keys = ['beginner', 'intermediate', 'advanced', 'family'] as const;
  if (!keys.every((k) => typeof o[k] === 'string')) return null;
  return {
    beginner: o.beginner as string,
    intermediate: o.intermediate as string,
    advanced: o.advanced as string,
    family: o.family as string,
  };
}

export function derivedEnvelope(row: SetupRow, userId: string): KaiObjectEnvelope {
  return envelope({
    id: `derived:graded_setup:${row.id}`,
    type: 'graded_setup',
    payload: gradedSetupFromRow(row, row.catalyst),
    model: DETERMINISTIC_MODEL,
    refs: { setup_id: row.id, user_id: userId, symbol: row.symbol },
  });
}
