/**
 * WEB PUSH — the browser half of "one notification, two transports".
 *
 * The whole transaction is three steps and each one can fail in a way the user
 * has to be told about in words:
 *
 *   1. the service worker registers          (needs a secure context)
 *   2. the browser grants permission         (once, ever, per origin)
 *   3. the browser mints a subscription      (endpoint + two encryption keys)
 *      against the SERVER's VAPID public key, and we hand it to the registry
 *
 * The keys in step 3 are generated by the browser and never by us. We store
 * them so the server can encrypt to this browser and nobody in between — not
 * Mozilla, not Google — can read the sentence.
 *
 * PERMISSION IS NEVER REQUESTED HERE ON LOAD. `subscribeWeb()` is only called
 * from a surface the user opened (§4.3), and a browser that has already said
 * no is never asked again — `Notification.permission === 'denied'` is a final
 * answer that only the browser's own site settings can change.
 */
import type { PushDevice } from '../../lib/types';
import { api } from '../../lib/api';
import { deviceLabel } from './capability';

export type WebPermission = 'granted' | 'denied' | 'default';

declare global {
  interface Window {
    /** Set by public/index.html so the first tap never races registration. */
    __cheatcodeSW?: Promise<ServiceWorkerRegistration | null>;
  }
}

export function webPermission(): WebPermission {
  if (typeof window === 'undefined' || typeof window.Notification !== 'function') return 'default';
  return window.Notification.permission as WebPermission;
}

/**
 * The registration the page started at load, or one started now. Awaiting
 * `navigator.serviceWorker.ready` on its own can hang forever when nothing
 * ever registered, so we always have a concrete registration to wait on.
 */
export async function serviceWorkerRegistration(): Promise<ServiceWorkerRegistration | null> {
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return null;
  try {
    const started = window.__cheatcodeSW ?? navigator.serviceWorker.register('/sw.js', { scope: '/' });
    window.__cheatcodeSW = started;
    const reg = await started;
    if (!reg) return null;
    // `ready` resolves once a worker is ACTIVE. A registration whose worker is
    // still installing has no pushManager we can subscribe through.
    await navigator.serviceWorker.ready;
    return (await navigator.serviceWorker.getRegistration('/')) ?? reg;
  } catch {
    return null;
  }
}

/** VAPID keys travel as base64url text and PushManager wants raw bytes. */
export function urlBase64ToUint8Array(base64: string): Uint8Array {
  const padding = '='.repeat((4 - (base64.length % 4)) % 4);
  const normalised = (base64 + padding).replace(/-/g, '+').replace(/_/g, '/');
  const raw = window.atob(normalised);
  const out = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i += 1) out[i] = raw.charCodeAt(i);
  return out;
}

function keysOf(sub: PushSubscription): { p256dh: string; auth: string } | null {
  const json = sub.toJSON() as { keys?: { p256dh?: string; auth?: string } };
  const p256dh = json.keys?.p256dh;
  const auth = json.keys?.auth;
  return p256dh && auth ? { p256dh, auth } : null;
}

export type WebSubscribeResult =
  | { ok: true; device: PushDevice }
  | { ok: false; reason: 'denied' | 'no_sw' | 'no_key' | 'failed'; plain: string };

/**
 * Ask (if we may), subscribe, register. Called from a priming surface only.
 *
 * `vapidPublicKey` comes from `GET /push/subscriptions` — the server's own
 * answer about what it can sign for.
 */
export async function subscribeWeb(vapidPublicKey: string | null): Promise<WebSubscribeResult> {
  if (!vapidPublicKey) {
    return {
      ok: false,
      reason: 'no_key',
      plain: 'The server has no signing key for browser notifications yet, so there is nothing to switch on.',
    };
  }

  const permission = webPermission();
  if (permission === 'denied') {
    return {
      ok: false,
      reason: 'denied',
      plain:
        'This browser is blocking notifications for the site. Open the padlock in the address bar, allow notifications, then come back.',
    };
  }

  // The ONE prompt. From here, and only from here.
  const answer = permission === 'granted' ? 'granted' : await window.Notification.requestPermission();
  if (answer !== 'granted') {
    return {
      ok: false,
      reason: 'denied',
      plain: 'You left notifications off. Everything still lands in your inbox, and you can turn them on here later.',
    };
  }

  const reg = await serviceWorkerRegistration();
  if (!reg || !reg.pushManager) {
    return {
      ok: false,
      reason: 'no_sw',
      plain: 'The background worker this browser needs did not start. Reload the page and try again.',
    };
  }

  let sub: PushSubscription;
  try {
    // An existing subscription is reused unless it was minted against a
    // different key — in which case it can never be delivered to and has to be
    // replaced rather than re-registered.
    const existing = await reg.pushManager.getSubscription();
    const wanted = urlBase64ToUint8Array(vapidPublicKey);
    if (existing) {
      const current = new Uint8Array(existing.options?.applicationServerKey ?? new ArrayBuffer(0));
      const same = current.length === wanted.length && current.every((b, i) => b === wanted[i]);
      if (!same) await existing.unsubscribe();
      sub = same ? existing : await reg.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: wanted as BufferSource });
    } else {
      sub = await reg.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: wanted as BufferSource });
    }
  } catch (e) {
    return {
      ok: false,
      reason: 'failed',
      plain: `This browser refused to set up notifications${e instanceof Error && e.message ? `: ${e.message}` : '.'}`,
    };
  }

  const keys = keysOf(sub);
  if (!keys) {
    // Storable and undeliverable by contract (§12.1). Registering it anyway
    // would leave a row the sender can only ever mark stale.
    return {
      ok: false,
      reason: 'failed',
      plain: 'This browser did not hand over the keys needed to encrypt a notification to it.',
    };
  }

  const device = await api.registerPush({
    transport: 'web',
    handle: sub.endpoint,
    keys,
    platform: 'web',
    device_label: deviceLabel(),
  });
  return { ok: true, device };
}

/** Drop the browser's own subscription. The server row is revoked separately. */
export async function unsubscribeWeb(): Promise<void> {
  try {
    const reg = await serviceWorkerRegistration();
    const sub = await reg?.pushManager?.getSubscription();
    if (sub) await sub.unsubscribe();
  } catch {
    /* the server row is the truth; a stale browser subscription 410s and is pruned */
  }
}

/** The endpoint this browser currently holds, so the UI can say "this device". */
export async function currentEndpoint(): Promise<string | null> {
  try {
    const reg = await serviceWorkerRegistration();
    const sub = await reg?.pushManager?.getSubscription();
    return sub?.endpoint ?? null;
  } catch {
    return null;
  }
}
