/**
 * Build the chart page.
 *
 *   node chart-web/build.mjs        →  apps/mobile/assets/chart/index.html
 *
 * NO BUNDLER, ON PURPOSE. `lightweight-charts` ships a standalone IIFE build
 * that puts `window.LightweightCharts` on the page with no module system at all,
 * and our own sources are plain scripts that share one closure. So the "build"
 * is: read the library, read src/*.js in filename order, read the CSS, read the
 * fonts, and write one file. That keeps the toolchain at exactly the two
 * dependencies the brief allows, and it keeps the output auditable — you can
 * open the committed HTML and read every line that will run on the device.
 *
 * THE OUTPUT IS COMMITTED. It is an app asset, not a build artifact: Metro
 * serves it to the WebView, and a device must never be waiting on a build step.
 * Re-run this after touching anything in chart-web/src and commit the result.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const APP = path.resolve(HERE, '..');
const OUT = path.join(APP, 'assets', 'chart', 'index.html');

const LIB = path.join(
  APP, 'node_modules', 'lightweight-charts', 'dist', 'lightweight-charts.standalone.production.js'
);

/**
 * JetBrains Mono, inlined.
 *
 * The page cannot reach the network and cannot see the app's loaded fonts — a
 * WebView is its own document with its own font stack. Two weights (400 for
 * axis numerals, 500 for chips and the rail) are embedded as base64 so the
 * chart's numbers are the same numerals as the rest of the app. Everything else
 * falls back to the platform mono, which is why `font-display: swap` is safe:
 * first paint uses SF Mono and swaps once JetBrains has decoded, so the font
 * never sits in front of the chart appearing.
 */
const FONTS = [
  { weight: 400, file: '400Regular/JetBrainsMono_400Regular.ttf' },
  { weight: 500, file: '500Medium/JetBrainsMono_500Medium.ttf' },
];

const esc = (s) => s.replace(/<\/script>/gi, '<\\/script>');

async function main() {
  const lib = await fs.readFile(LIB, 'utf8');
  const css = await fs.readFile(path.join(HERE, 'src', 'style.css'), 'utf8');

  const names = (await fs.readdir(path.join(HERE, 'src')))
    .filter((f) => f.endsWith('.js'))
    .sort();
  const parts = [];
  for (const n of names) {
    parts.push(`/* ===== chart-web/src/${n} ===== */\n` + (await fs.readFile(path.join(HERE, 'src', n), 'utf8')));
  }

  const faces = [];
  for (const f of FONTS) {
    const p = path.join(APP, 'node_modules', '@expo-google-fonts', 'jetbrains-mono', f.file);
    try {
      const b = await fs.readFile(p);
      faces.push(
        `@font-face{font-family:"JetBrains Mono";font-style:normal;font-weight:${f.weight};` +
        `font-display:swap;src:url(data:font/ttf;base64,${b.toString('base64')}) format("truetype")}`
      );
    } catch {
      console.warn(`  ! JetBrains Mono ${f.weight} not found at ${p} — falling back to the platform mono.`);
    }
  }

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
<meta name="color-scheme" content="dark">
<title>Cheat Code chart</title>
<style>${faces.join('')}</style>
<style>${css}</style>
</head>
<body>
<div id="root"></div>
<script>${esc(lib)}</script>
<script>
/* Cheat Code AI — the chart Kai drives (LIVE-1).
   Generated by chart-web/build.mjs. Edit chart-web/src/*.js, then re-run it. */
(function(){
"use strict";
${esc(parts.join('\n\n'))}
})();
</script>
</body>
</html>
`;

  await fs.mkdir(path.dirname(OUT), { recursive: true });
  await fs.writeFile(OUT, html, 'utf8');
  const kb = (Buffer.byteLength(html) / 1024).toFixed(0);
  console.log(`chart-web → ${path.relative(APP, OUT)}  (${kb} KB, ${names.length} sources, ${faces.length} font faces)`);
}

main().catch((e) => { console.error(e); process.exit(1); });
