import React from 'react';
import { View } from 'react-native';
import { color, alpha } from './theme';
import { ActionButton, Badge, BottomNavigation, Divider, Eyebrow, FeedbackState, FormField, IconButton, KitText, LoadingState, MessageComposer, Row, ScreenFrame, SectionHeading, SegmentedControl, SelectionRow, SettingToggle, Stack, type MainTab } from './primitives';
import { CompanyIdentity, CompactTradeRow, MetricStrip, OrderSummary, PriceLevels, RiskRewardBar, TradeChart, TradeIdeaPreview, TradeLifecycle } from './trading';
import { BeltEmblem, CandleAnatomy, LessonPath, OwnershipGrid, ProgressRing, SkillChecklist, VideoLesson } from './learning';
import { CircleStories, ConversationThread, KaiMessage, MemberProfile, ThreadHistory } from './conversation';
import { PersonalPlan, ProductReveal } from './onboarding';
import { KitIcon } from './icons';
import { price, riskReward } from '../../../../../packages/trade-ui/model';
import { screenCatalog, type KitAction, type KitData, type KitState, type ScreenId } from './contracts';
export type KitScreenProps = {
  screen: ScreenId; data: KitData; state: KitState; onAction: (action: KitAction) => void;
  onSend: (text: string, context: { screen: ScreenId; roomId: string; threadId?: string; ideaId: string }) => Promise<void>;
  /** Use false inside an existing Expo tab navigator. Never mount two tab bars. */
  showNavigation?: boolean; insets?: { top: number; bottom: number };
  loadState?: 'ready' | 'loading' | 'error'; errorMessage?: string;
};
const onboarding: readonly ScreenId[] = ['identify','reveal','curiosity','plan','signup','preferences'];
const utility: readonly ScreenId[] = ['account','guidance','notifications','membership','history','room-switcher'];
function tabFor(screen: ScreenId): MainTab {
  if (['community','discussion','room-switcher'].includes(screen)) return 'community';
  if (['account','guidance','notifications','membership','belt','skills','training','lesson','video','lesson-complete'].includes(screen)) return 'account';
  if (['analysis','order-review','order-pending','position','debrief'].includes(screen)) return 'trade';
  if (['alerts','setup','research','company'].includes(screen)) return 'alerts';
  return 'home';
}
/** Every screen is a composition of exported product objects. No service calls or fixture imports. */
export function KitScreen({ screen, data: d, state: st, onAction, onSend, showNavigation = true, insets, loadState = 'ready', errorMessage }: KitScreenProps) {
  const navigate = (screen: ScreenId) => onAction({ type: 'navigate', screen });
  const update = (patch: Partial<KitState>) => onAction({ type: 'state', patch });
  const isOnboarding = onboarding.includes(screen); const isHome = screen.startsWith('home-') || screen === 'quiet';
  const isCommunity = screen === 'community' || screen === 'discussion';
  const invest = screen === 'home-invest' || screen === 'research' || screen === 'company';
  const meta = screenCatalog.find(item => item.id === screen)!;
  const send = (text: string) => onSend(text, { screen, roomId: st.roomId, threadId: st.threadId, ideaId: d.trade.id });
  const review = () => onAction({ type: 'open-idea', id: d.trade.id });
  const chart = <TradeChart idea={d.trade} selected={st.level} />;
  const company = <CompanyIdentity symbol={d.trade.symbol} company={d.trade.company} grade={d.trade.grade} noLogo={d.noLogo} />;
  const levels = <PriceLevels idea={d.trade} selected={st.level} onSelect={level => update({ level })} />;
  const kaiNote = <KaiMessage compact text={d.selectedLevelNotes[st.level]} />;
  let body: React.ReactNode;
  switch (screen) {
    case 'identify': body = <><SectionHeading eyebrow="YOUR STARTING POINT" title="What do you want CheatCode to help you do?" /><Stack gap={4}>{([{ id:'learn',title:'Learn',detail:'Make your first stock make sense.',icon:'book' },{ id:'swing',title:'Swing',detail:'Find setups. Build a clear plan.',icon:'alerts' },{ id:'pro',title:'Pro',detail:'Analyze charts. Refine your process.',icon:'trade' }] as const).map(p => <SelectionRow key={p.id} title={p.title} detail={p.detail} icon={p.icon} selected={st.persona === p.id} onPress={() => update({ persona: p.id })} />)}</Stack><ActionButton label="Find my starting point" onPress={() => navigate('reveal')} /></>; break;
    case 'reveal': body = <><SectionHeading title="A clearer way to invest and trade." /><ProductReveal /><KitText align="center" c={color.violetLight}>Kai connects all of it.</KitText><ActionButton label="Show me" onPress={() => navigate(st.persona === 'learn' ? 'lesson' : st.persona === 'swing' ? 'setup' : 'analysis')} /></>; break;
    case 'curiosity': body = <><SectionHeading eyebrow="FOLLOW YOUR CURIOSITY" title="What would you like to explore next?" /><Stack gap={2}>{(st.persona === 'learn' ? ['Finding good companies','Understanding charts','Learning to trade'] : st.persona === 'swing' ? ['Why Kai likes it','What traders are saying','What happens after I track it'] : ['Build the trade plan','Review my execution','See belt progression']).map(interest => <SelectionRow key={interest} title={interest} selected={st.interest === interest} onPress={() => update({ interest })} />)}</Stack><ActionButton label="Show me" disabled={!st.interest} onPress={() => navigate(st.interest.includes('companies') ? 'company' : st.interest.includes('traders') ? 'discussion' : st.interest.includes('belt') ? 'belt' : st.interest.includes('execution') ? 'debrief' : st.interest.includes('track') ? 'position' : st.interest.includes('trade plan') ? 'order-review' : st.interest.includes('trade') ? 'training' : 'analysis')} /></>; break;
    case 'plan': body = <><SectionHeading title="Built around what you told us." subtitle="Your interests. Your starting point." /><PersonalPlan {...d.plan} /><ActionButton label="Join early access" onPress={() => onAction({ type:'join-early-access' })} /><KitText size={13} c={color.muted}>No payment today.</KitText></>; break;
    case 'signup': body = <><SectionHeading title="Keep your momentum." subtitle="Save your path and conversations with Kai." /><FormField label="Email" email value={st.email} onChange={email => update({ email })} /><FormField label="Password" secure value={st.password} onChange={password => update({ password })} /><KitText size={13} c={color.muted}>Your selected path: {st.persona === 'learn' ? 'Learn' : st.persona === 'swing' ? 'Swing' : 'Pro'}</KitText>{st.formError && <KitText accessibilityRole="alert" c={color.red}>{st.formError}</KitText>}<ActionButton label="Create account" busy={st.busy} disabled={!st.email.trim() || !st.password} onPress={() => onAction({ type:'create-account',email:st.email,password:st.password })} /><ActionButton variant="secondary" label="Privacy & terms" icon={false} onPress={() => onAction({ type:'open-privacy' })} /></>; break;
    case 'preferences': body = <><KaiMessage text="Let's make this feel like your space." /><SectionHeading title="Start with confidence." /><SelectionRow title="Guided explanations" detail="Plain language, one step at a time." selected={st.guidance === 'guided'} onPress={() => update({ guidance:st.guidance === 'guided' ? 'concise' : 'guided' })} /><MetricStrip items={[{ label:'Practice balance',value:d.profile.balanceLabel }]} /><Badge>Paper trading · no real money</Badge><ActionButton label="Meet Kai" onPress={() => onAction({ type:'confirm-preferences' })} /></>; break;
    case 'home-beginner': body = <><KaiMessage text={d.greeting} /><Divider /><SectionHeading eyebrow="3-MINUTE FIRST STEP" title="What do you own?" subtitle="A simple way to see what a share means." /><OwnershipGrid selected={10} /><ActionButton label="Try the lesson" onPress={() => navigate('lesson')} /><ActionButton variant="secondary" label="Explore a company" onPress={() => navigate('company')} /></>; break;
    case 'home-developing': body = <><KaiMessage text={d.greeting} /><Divider /><SectionHeading eyebrow="PRACTICE EXAMPLE" title="Map your trade." subtitle="A great entry means nothing without a plan." />{company}{chart}{kaiNote}<ActionButton label="Practise the plan" onPress={() => navigate('order-review')} /></>; break;
    case 'home-ready': body = <><KaiMessage text={d.greeting} /><Divider /><SectionHeading eyebrow="SETUP PREVIEW" title="The breakout. The retest." subtitle="A clear setup with a defined plan." />{company}{chart}<TradeLifecycle status={d.trade.status} />{levels}<ActionButton label="Review setup" onPress={review} /></>; break;
    case 'home-invest': body = <><KaiMessage text={d.greeting} /><Divider /><SectionHeading eyebrow="UNDERSTAND THE BUSINESS" title="Start with a company you know." /><CompanyIdentity symbol={d.company.symbol} company={d.company.name} noLogo={d.noLogo} /><KitText size={23}>{d.company.description}</KitText><Row><KitIcon name="book" ink={color.cyan} /><KitText c={color.muted}>What it makes → how it earns</KitText></Row><ActionButton label="Understand this company" onPress={() => navigate('company')} /><ActionButton variant="secondary" label="Explore the research desk" onPress={() => navigate('research')} /></>; break;
    case 'research': body = <><SectionHeading title="Good investing starts with understanding." subtitle="Explore the business before the price." /><Stack gap={0}>{d.companies.map(c => <SelectionRow key={c.symbol} title={`${c.symbol} · ${c.name}`} detail={c.description} icon="search" onPress={() => onAction({ type:'open-company',symbol:c.symbol })} />)}</Stack><KaiMessage compact text="Start with how a company earns money. Then ask what could change." /></>; break;
    case 'company': body = <><CompanyIdentity symbol={d.company.symbol} company={d.company.name} noLogo={d.noLogo} /><Badge>Long-term investing</Badge><SectionHeading title="Understand what you own." /><KitText size={24}>{d.company.description}</KitText><Divider /><Stack gap={7}><Eyebrow>WHY WATCH</Eyebrow><KitText>{d.company.whyWatch}</KitText></Stack><Stack gap={7}><Eyebrow>WHAT COULD GO WRONG</Eyebrow><KitText c={color.muted}>{d.company.risk}</KitText></Stack><ActionButton label="Ask Kai about this company" variant="kai" onPress={() => navigate('kai')} /><KitText size={12} c={color.muted}>{d.company.sourceLabel}</KitText></>; break;
    case 'alerts': { const ideas = d.ideas.filter(idea => st.alertFilter === 'active' ? ['entry_reached','active'].includes(idea.status) : st.alertFilter === 'watching' ? idea.status === 'watching' : ['closed','expired','invalidated'].includes(idea.status)); body = <><SectionHeading title="Trade ideas" subtitle="Real setups. Clear plans. Less noise." /><SegmentedControl options={(['active','watching','history'] as const).map(id => ({ id,label:id[0].toUpperCase()+id.slice(1) }))} value={st.alertFilter} onChange={value => update({ alertFilter:value as KitState['alertFilter'] })} />{ideas.length ? <Stack gap={12}><TradeIdeaPreview idea={ideas[0]} noLogo={d.noLogo} onOpen={() => onAction({ type:'open-idea',id:ideas[0].id })} />{ideas.slice(1).map(idea => <CompactTradeRow key={idea.id} idea={idea} noLogo={d.noLogo} onOpen={() => onAction({ type:'open-idea',id:idea.id })} />)}</Stack> : <FeedbackState icon="alerts" title="Nothing here yet." message="When a setup enters this stage, it will appear here." />}<KitText size={11} c={color.muted}>{d.trade.dataLabel}</KitText></>; break; }
    case 'setup': body = <>{company}<SectionHeading title={d.trade.title} subtitle={d.trade.summary} />{chart}{levels}{kaiNote}<RiskRewardBar idea={d.trade} /><TradeLifecycle status={d.trade.status} /><ActionButton label={st.watched ? "Watching setup" : "Watch setup"} disabled={st.watched || ['closed','expired','invalidated'].includes(d.trade.status)} onPress={() => onAction({ type:'watch-idea',id:d.trade.id })} /><ActionButton label="Analyze the chart" variant="secondary" onPress={() => navigate('analysis')} /><KitText size={11} c={color.muted}>{d.trade.dataLabel}</KitText></>; break;
    case 'analysis': body = <>{company}<Badge tone={d.execution === 'live' ? 'risk' : 'neutral'}>{d.execution === 'paper' ? 'Paper · practice mode' : 'Live · real money'}</Badge><SegmentedControl options={[{id:'look',label:'1 Look'},{id:'decide',label:'2 Decide'},{id:'plan',label:'3 Plan'}]} value="look" onChange={value => value === 'look' ? onAction({ type:'analyze-chart',ideaId:d.trade.id }) : navigate(value === 'decide' ? 'setup' : 'order-review')} /><SectionHeading title="Find the story in the chart." /><TradeChart idea={d.trade} height={320} annotated selected={st.level} />{kaiNote}<ActionButton label={d.execution === 'paper' ? 'Build a paper plan' : 'Build a trade plan'} onPress={() => navigate('order-review')} /></>; break;
    case 'order-review': body = <><SectionHeading title="Define the risk first." />{company}<OrderSummary idea={d.trade} execution={d.execution} quantity={st.quantity} onQuantityChange={quantity => update({ quantity })} />{levels}<RiskRewardBar idea={d.trade} /><ActionButton label={d.execution === 'paper' ? 'Submit paper order' : 'Confirm live order'} busy={st.busy} disabled={!riskReward(d.trade) || !Number.isInteger(st.quantity) || st.quantity < 1} onPress={() => onAction({ type:'submit-order',ideaId:d.trade.id,quantity:st.quantity,execution:d.execution })} /><KitText size={13} c={color.muted}>{d.execution === 'paper' ? 'Simulated execution. No real money is used.' : 'This sends an order to your connected brokerage.'}</KitText></>; break;
    case 'order-pending': body = <><Badge tone={d.execution === 'live' ? 'risk' : 'neutral'}>{d.execution === 'paper' ? 'Paper order' : 'Live order'}</Badge><SectionHeading title={d.order.statusLabel} subtitle="Submission is not a fill." /><View style={{ alignItems:'center',paddingVertical:22 }}><ProgressRing progress={d.order.requested > 0 ? d.order.filled/d.order.requested : 0} ink={color.cyan}><KitIcon name="clock" size={40} ink={color.cyan} /></ProgressRing></View>{company}<MetricStrip items={[{label:'Shares filled',value:`${d.order.filled}/${d.order.requested}`},{label:'Planned entry',value:price(d.trade.entry),ink:color.cyan}]} /><KitText c={color.muted}>{d.order.asOf}</KitText><ActionButton label="Back to trade idea" variant="secondary" onPress={() => navigate('setup')} /></>; break;
    case 'position': { const pnl = d.position.current === null ? null : (d.position.current-d.position.entry)*d.position.shares*(d.trade.direction === 'long' ? 1 : -1); body = <><Badge tone={d.execution === 'paper' ? 'neutral':'risk'}>{d.execution === 'paper' ? 'Paper position':'Live position'}</Badge>{company}<SectionHeading title="Your plan is in motion." />{chart}<MetricStrip items={[{label:'Unrealized P&L',value:pnl === null ? '—' : `${pnl >= 0 ? '+' : '−'}$${price(Math.abs(pnl))}`,ink:pnl === null ? color.muted : pnl >= 0 ? color.green:color.red},{label:'Shares',value:String(d.position.shares)}]} />{levels}<KaiMessage compact text="Keep the stop where the idea is wrong. A moving price is not a new plan." /><KitText size={12} c={color.muted}>{d.position.asOf}</KitText><ActionButton label="Review the plan" variant="secondary" onPress={() => navigate('setup')} /></>; break; }
    case 'debrief': { const pnl = (d.review.exitPrice-d.review.entry)*d.review.shares*(d.trade.direction === 'long'?1:-1); body = <><SectionHeading eyebrow="PROCESS BEFORE PROFIT" title={d.review.title} /><MetricStrip items={[{label:`Result · ${d.review.shares} shares`,value:`${pnl>=0?'+':'−'}$${price(Math.abs(pnl))}`,ink:pnl>=0?color.green:color.red},{label:'Exit',value:price(d.review.exitPrice)}]} /><Divider /><SkillChecklist skills={d.skills} /><KaiMessage text={d.review.lesson} compact /><ActionButton label="Practise the next skill" onPress={() => navigate('training')} /></>; break; }
    case 'quiet': body = <><KaiMessage text="Nothing needs your attention right now." /><FeedbackState icon="clock" title="A quiet market is useful time." message="Build a skill while you wait for a setup that fits." /><LessonPath lessons={d.lessons.slice(0,1)} onOpen={id => onAction({ type:'open-lesson',id })} /><ActionButton label="Practise reading a candle" onPress={() => navigate('video')} /></>; break;
    case 'offline': body = <><FeedbackState title="You're offline." message={d.connection.message} /><Badge>Last saved · {d.connection.lastUpdated}</Badge>{company}{chart}<KitText size={13} c={color.muted}>This is saved information. Refresh before making a new decision.</KitText><ActionButton label="Try reconnecting" busy={st.busy} onPress={() => onAction({ type:'retry' })} /></>; break;
    case 'training': body = <><SectionHeading eyebrow="YOUR LEARNING PATH" title="One useful skill at a time." /><Row><ProgressRing progress={d.profile.progress} size={62}><KitIcon name="book" ink={color.volt} /></ProgressRing><Stack gap={4}><KitText>{d.profile.rank[0].toUpperCase()+d.profile.rank.slice(1)} Belt foundations</KitText><KitText size={13} c={color.muted}>Learn → practise → demonstrate</KitText></Stack></Row><LessonPath lessons={d.lessons} onOpen={id => onAction({ type:'open-lesson',id })} /></>; break;
    case 'lesson': body = <><SectionHeading eyebrow="OWNERSHIP / INTERACTIVE LESSON" title="What did you actually buy?" subtitle="Choose shares in our example company." /><OwnershipGrid selected={st.ownedShares} onChange={ownedShares => update({ ownedShares })} /><KaiMessage compact text="That's a stock. Ownership, not a lottery ticket." /><ActionButton label="Check my understanding" onPress={() => onAction({ type:'complete-lesson',ownedShares:st.ownedShares })} /></>; break;
    case 'video': body = <><SectionHeading eyebrow="WATCH / THEN TRY" title="Read a candle." /><VideoLesson title={d.video.title} creator={d.video.creator} duration={d.video.duration} onPlay={() => onAction({ type:'play-video',lessonId:d.video.lessonId })} onTranscript={() => onAction({ type:'open-transcript',lessonId:d.video.lessonId })} /><CandleAnatomy selected={st.candlePart} onSelect={candlePart => update({ candlePart })} /></>; break;
    case 'lesson-complete': body = <><View style={{ alignItems:'center',paddingTop:24 }}><ProgressRing progress={1} ink={color.green}><KitIcon name="check" size={54} ink={color.green} /></ProgressRing></View><SectionHeading title="You understand ownership." subtitle="A share represents part of a company." /><KaiMessage compact text="Now connect the idea to a real business." /><ActionButton label="Explore a company" onPress={() => navigate('company')} /><ActionButton variant="secondary" label="See my progress" onPress={() => navigate('skills')} /></>; break;
    case 'skills': body = <><SectionHeading title="Proof of progress." subtitle="Demonstrate the skill. Then unlock the next step." /><SkillChecklist skills={d.skills} /><KaiMessage compact text="Your process earns the next belt. Profit alone doesn't." /><ActionButton label="Continue practising" onPress={() => navigate('training')} /></>; break;
    case 'belt': body = <><SectionHeading eyebrow="YOUR CURRENT BELT" title={`${d.profile.rank[0].toUpperCase()+d.profile.rank.slice(1)} Belt`} /><View style={{ alignItems:'center' }}><ProgressRing progress={d.profile.progress} size={230} label="Next belt progress"><BeltEmblem rank={d.profile.rank} /><KitText mono size={26}>{Math.round(d.profile.progress*100)}%</KitText></ProgressRing></View><SectionHeading eyebrow="NEXT UNLOCK" title={`${d.profile.nextRank} Belt`} /><SkillChecklist skills={d.skills} /><KitText size={13} c={color.muted}>Knowledge. Chart reading. Planning. Verified process.</KitText><ActionButton label="Build the next skill" onPress={() => navigate('training')} /></>; break;
    case 'community': body = <><CircleStories rooms={d.rooms} onOpen={id => onAction({ type:'open-room',id })} /><SelectionRow title={d.rooms.find(r=>r.id===st.roomId)?.title ?? 'Main room'} detail="Choose a conversation" icon="community" onPress={() => navigate('room-switcher')} /><CompactTradeRow idea={d.trade} noLogo={d.noLogo} onOpen={() => navigate('discussion')} /><ConversationThread messages={d.messages} /></>; break;
    case 'room-switcher': body = <><SectionHeading title="Find your conversation." /><Stack gap={0}>{d.rooms.map(room => <SelectionRow key={room.id} title={room.title} detail={`${room.membersLabel} · ${room.remainingLabel}`} selected={room.id===st.roomId} onPress={() => onAction({ type:'open-room',id:room.id })} />)}</Stack><KitText size={13} c={color.muted}>Switching rooms keeps your trading mode unchanged.</KitText></>; break;
    case 'discussion': body = <><CompactTradeRow idea={d.trade} noLogo={d.noLogo} onOpen={review} /><SectionHeading title="Where is the idea wrong?" /><ConversationThread messages={d.messages} /><ActionButton label="Ask Kai to explain the stop" variant="kai" onPress={() => navigate('kai')} /></>; break;
    case 'history': body = <><ActionButton label="New conversation" icon="plus" onPress={() => onAction({ type:'new-thread' })} /><ThreadHistory threads={d.threads} selected={st.threadId} onOpen={id => onAction({ type:'open-thread',id })} /></>; break;
    case 'kai': body = <><Badge tone="kai">Context · {d.trade.symbol}</Badge><KaiMessage text={d.selectedLevelNotes[st.level]} /><TradeChart idea={d.trade} annotated />{levels}<ConversationThread messages={d.messages.filter(message=>message.isKai || message.name===d.profile.name)} /></>; break;
    case 'account': body = <><MemberProfile name={d.profile.name} rank={d.profile.rank} subtitle={`${st.guidance==='guided'?'Guided':'Concise'} · ${d.execution==='paper'?'Paper':'Live'}`} /><Stack gap={0}><SelectionRow title="Learning & belts" icon="book" detail="Your skills and next milestone" onPress={() => navigate('belt')} /><SelectionRow title="Guidance & accessibility" icon="account" onPress={() => navigate('guidance')} /><SelectionRow title="Notifications" icon="alerts" onPress={() => navigate('notifications')} /><SelectionRow title="Plan & credits" icon="bolt" onPress={() => navigate('membership')} /><SelectionRow title="Privacy & security" icon="lock" onPress={() => onAction({ type:'open-privacy' })} /><SelectionRow title="Sign out" onPress={() => onAction({ type:'sign-out' })} /></Stack></>; break;
    case 'guidance': body = <><SectionHeading title="Make it feel right." /><Eyebrow>KAI EXPLANATIONS</Eyebrow><SegmentedControl options={[{id:'guided',label:'Guided'},{id:'concise',label:'Concise'}]} value={st.guidance} onChange={guidance=>update({ guidance:guidance as KitState['guidance'] })} /><KaiMessage compact text={st.guidance==='guided'?'A stop marks the price where your original idea no longer holds.':'Stop: where the idea is wrong.'} /><Eyebrow>TEXT SIZE</Eyebrow><SegmentedControl options={[{id:'1',label:'Default'},{id:'1.2',label:'Larger'},{id:'1.4',label:'Largest'}]} value={String(st.textScale)} onChange={scale=>update({ textScale:Number(scale) })} /><SettingToggle title="Reduce motion" detail="Keep transitions and product reveals still." value={st.reducedMotion} onChange={reducedMotion=>update({ reducedMotion })} /><Badge>{d.execution==='paper'?'Paper practice':'Live trading'}</Badge><KitText size={13} c={color.muted}>Trading mode is shown separately from guidance.</KitText></>; break;
    case 'notifications': body = <><SectionHeading title="Only what matters." /><Badge>{d.notificationDelivery}</Badge><SettingToggle title="Setup updates" detail="When a tracked idea changes." value={st.setupNotifications} onChange={setupNotifications=>update({ setupNotifications })} /><SettingToggle title="Community replies" detail="Replies to your conversations." value={st.communityNotifications} onChange={communityNotifications=>update({ communityNotifications })} /><SettingToggle title="Quiet hours" detail="Pause nonessential notifications overnight." value={st.quietHours} onChange={quietHours=>update({ quietHours })} /><ActionButton label="Send a test notification" variant="secondary" busy={st.busy} onPress={()=>onAction({ type:'test-notification' })} /></>; break;
    case 'membership': body = <><SectionHeading title={d.membership.name} subtitle="Your current access, clearly explained." /><MetricStrip items={[{label:'Kai questions used',value:`${d.membership.creditsUsed}/${d.membership.creditsTotal}`}]} /><ProgressRing progress={d.membership.creditsTotal>0?d.membership.creditsUsed/d.membership.creditsTotal:0} size={90}><KitIcon name="bolt" ink={color.violetLight} /></ProgressRing><KitText size={13} c={color.muted}>{d.membership.resetsLabel}</KitText><Stack gap={12}><Eyebrow>INCLUDED</Eyebrow>{d.membership.included.map(label=><Row key={label}><KitIcon name="check" ink={color.green} size={18} /><KitText style={{flex:1}}>{label}</KitText></Row>)}</Stack><Divider /><Stack gap={12}><Eyebrow>NOT INCLUDED IN THIS PLAN</Eyebrow>{d.membership.excluded.map(label=><Row key={label}><KitIcon name="lock" ink={color.muted} size={18} /><KitText c={color.muted} style={{flex:1}}>{label}</KitText></Row>)}</Stack></>; break;
  }
  if (loadState === 'loading') body = <LoadingState />;
  if (loadState === 'error') body = <FeedbackState title="We couldn't load this." message={errorMessage ?? 'Try again. Your saved work has not been changed.'} action={<ActionButton label="Try again" onPress={() => onAction({ type: 'retry' })} />} />;
  const tab = tabFor(screen);
  const navigation = !isOnboarding && showNavigation ? <BottomNavigation active={tab} invest={invest} onChange={tab => navigate(tab==='home' ? (invest?'home-invest':st.persona==='learn'?'home-beginner':st.persona==='pro'?'home-ready':'home-developing') : tab==='alerts' ? invest?'research':'alerts' : tab==='trade'?'analysis':tab)} /> : undefined;
  const dock = loadState === 'ready' && !isOnboarding && !utility.includes(screen) ? <MessageComposer key={isCommunity ? `room-${st.roomId}` : `kai-${st.threadId??'new'}`} kind={isCommunity?'community':'kai'} disabled={screen==='offline'} onSend={send} /> : undefined;
  return <ScreenFrame contentKey={screen} title={isHome || isOnboarding || screen==='alerts' ? 'CheatCode' : meta.title} insets={insets} leading={screen==='identify' ? undefined : <IconButton name={isHome?'menu':'back'} label={isHome?'Conversation history':'Go back'} onPress={()=>isHome?navigate('history'):onAction({type:'back'})} />} trailing={isHome ? <IconButton name="plus" label="New conversation" onPress={()=>onAction({type:'new-thread'})} /> : screen==='alerts'?<Badge>{st.persona==='pro'?'Day trade':'Swing'}</Badge>:undefined} dock={dock} navigation={navigation}>{body}</ScreenFrame>;
}

export type ScreenCompositionProps = Omit<KitScreenProps, 'screen'>;
export function IdentifyScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="identify" />; }
export function ValueRevealScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="reveal" />; }
export function CuriosityScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="curiosity" />; }
export function PersonalizedPlanScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="plan" />; }
export function SignupScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="signup" />; }
export function StartingPreferencesScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="preferences" />; }
export function BeginnerHomeScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="home-beginner" />; }
export function DevelopingHomeScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="home-developing" />; }
export function TradeReadyHomeScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="home-ready" />; }
export function InvestorHomeScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="home-invest" />; }
export function ResearchScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="research" />; }
export function CompanyScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="company" />; }
export function AlertsScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="alerts" />; }
export function SetupDetailScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="setup" />; }
export function ChartAnalysisScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="analysis" />; }
export function OrderReviewScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="order-review" />; }
export function OrderPendingScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="order-pending" />; }
export function PositionScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="position" />; }
export function TradeDebriefScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="debrief" />; }
export function QuietMarketScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="quiet" />; }
export function OfflineScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="offline" />; }
export function TrainingPathScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="training" />; }
export function OwnershipLessonScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="lesson" />; }
export function VideoLessonScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="video" />; }
export function LessonCompleteScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="lesson-complete" />; }
export function SkillProgressScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="skills" />; }
export function BeltProfileScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="belt" />; }
export function CommunityScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="community" />; }
export function RoomSwitcherScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="room-switcher" />; }
export function DiscussionScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="discussion" />; }
export function ConversationHistoryScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="history" />; }
export function KaiChatScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="kai" />; }
export function AccountScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="account" />; }
export function GuidanceScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="guidance" />; }
export function NotificationsScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="notifications" />; }
export function MembershipScreen(props: ScreenCompositionProps) { return <KitScreen {...props} screen="membership" />; }
